{% set name = "spams-cython" %}
{% set version = "1.0.0" %}
{% set sha256 = "c7a1e32bde4e0a7d6fd61fc3922f7349d66a44b5cf2a8ab6ec14167150daa0ad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - cyspams
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/getspams/spams-cython/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: SPArse Modeling Software (SPAMS) Cython interface
  description: |
    This package exposes convenient interfaces of some functions of the
    SPArse Modeling Software (SPAMS) C++ library, allowing them to be used
    from Cython code by releasing the Python Global Interpreter Lock (GIL).

extra:
  recipe-maintainers:
    - pauldmccarthy
